# https://taskfile.dev

version: "3"

env:
  CHART_DIR: "."

tasks:
  generate-crossplane-contrib-models:
    cmds:
      - ./scripts/generate-provider-sql-models.sh
  generate-upbound-models:
    cmds:
      - up dependency update-cache --project-file="project.yaml"
      - cp -r .up/kcl/models/* .
